import { Resource, ResourceType } from '@/types/index.ts';

export class ResourceFactory {
  static createResource(
    resourceData: Omit<Resource, 'id' | 'createdAt' | 'updatedAt'>,
  ): Resource {
    // In a more complex scenario, different resource types might have different
    // properties or require different initialization logic. For now, we'll
    // simply ensure the type is correctly assigned.
    switch (resourceData.type) {
      case ResourceType.ARTICLE:
      case ResourceType.VIDEO:
      case ResourceType.PDF:
      case ResourceType.LINK:
        return {
          ...resourceData,
          id: '', // Placeholder, will be generated by BaseModel
          createdAt: new Date(),
          updatedAt: new Date(),
        } as Resource;
      default:
        throw new Error('Unknown resource type');
    }
  }
}
